#!/bin/sh
# NSS ECM owns forwarding acceleration; do not compete with nft flowtables.
uci set firewall.@defaults[0].flow_offloading='0'
uci set firewall.@defaults[0].flow_offloading_hw='0'
uci commit firewall
exit 0
